inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'extensions/**/*'
    - 'vendor/**/*'

AllCops:
  StyleGuideCopsOnly: true

# Uncomment when lines are under 100 lenghth
# Metrics/LineLength:
#   Max: 100

Metrics/MethodLength:
  Enabled: false

Style/Alias:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrivialAccessors:
  ExactNameMatch: true
