sonar.sources=.
sonar.exclusions=data/**/*,sql/**/*,tests/**/*,resources/lib/**/*
sonar.tests=tests/phpunit,tests/qunit
sonar.test.exclusions=tests/phpunit/data
sonar.issue.ignore.multicriteria=s131
sonar.issue.ignore.multicriteria.s131.ruleKey=php:S131
sonar.issue.ignore.multicriteria.s131.resourceKey=**/*
