'use strict';

/* eslint-env jest */
/* eslint-disable camelcase */

// config.json is generated by ResourceLoader at build time, so mock it here.
const mockConfig = { TranslateEnableEventLogging: true };
jest.mock(
	'../../../resources/src/ext.translate.eventlogginghelpers/config.json',
	() => mockConfig,
	{ virtual: true }
);

const eventLoggingHelpers = require(
	'../../../resources/src/ext.translate.eventlogginghelpers/index.js'
);

describe( 'ext.translate.eventlogginghelpers', () => {
	let sendMock;
	let isInSampleMock;
	let getInstrumentMock;

	beforeEach( () => {
		mockConfig.TranslateEnableEventLogging = true;
		sendMock = jest.fn();
		isInSampleMock = jest.fn( () => true );
		getInstrumentMock = jest.fn( () => ( { send: sendMock, isInSample: isInSampleMock } ) );
		global.mw = {
			testKitchen: {
				getInstrument: getInstrumentMock
			}
		};
	} );

	afterEach( () => {
		jest.clearAllMocks();
	} );

	describe( 'isEventLoggingEnabled', () => {
		it( 'reflects the TranslateEnableEventLogging config flag', () => {
			mockConfig.TranslateEnableEventLogging = true;
			expect( eventLoggingHelpers.isEventLoggingEnabled() ).toBe( true );

			mockConfig.TranslateEnableEventLogging = false;
			expect( eventLoggingHelpers.isEventLoggingEnabled() ).toBe( false );
		} );
	} );

	describe( 'logClickEvent', () => {
		it( 'sends a "click" event through the Test Kitchen instrument', () => {
			eventLoggingHelpers.logClickEvent( 'button', 'sidebar', { id: 42 } );

			expect( getInstrumentMock ).toHaveBeenCalledWith( 'translate-click-actions' );
			expect( sendMock ).toHaveBeenCalledWith( 'click', {
				translation: { id: 42 },
				action_subtype: 'button',
				action_source: 'sidebar'
			} );
		} );

		it( 'defaults translation to {} and omits absent optional fields', () => {
			eventLoggingHelpers.logClickEvent( null, null, null );

			expect( sendMock ).toHaveBeenCalledWith( 'click', { translation: {} } );
		} );

		it( 'does not send when event logging is disabled', () => {
			mockConfig.TranslateEnableEventLogging = false;

			eventLoggingHelpers.logClickEvent( 'button', 'sidebar', {} );

			expect( getInstrumentMock ).not.toHaveBeenCalled();
			expect( sendMock ).not.toHaveBeenCalled();
		} );
	} );

	describe( 'logEvent', () => {
		it( 'sends the given action through the Test Kitchen instrument', () => {
			eventLoggingHelpers.logEvent( 'publish', 'button', 'toolbar', { id: 7 } );

			expect( getInstrumentMock ).toHaveBeenCalledWith( 'translate-click-actions' );
			expect( sendMock ).toHaveBeenCalledWith( 'publish', {
				translation: { id: 7 },
				action_subtype: 'button',
				action_source: 'toolbar'
			} );
		} );

		it( 'defaults translation to {} and omits absent optional fields', () => {
			eventLoggingHelpers.logEvent( 'publish', null, null, null );

			expect( sendMock ).toHaveBeenCalledWith( 'publish', { translation: {} } );
		} );

		it( 'does not send when event logging is disabled', () => {
			mockConfig.TranslateEnableEventLogging = false;

			eventLoggingHelpers.logEvent( 'publish', null, null, null );

			expect( sendMock ).not.toHaveBeenCalled();
		} );
	} );

	describe( 'sampling', () => {
		it( 'does not send when the instrument is not in sample', () => {
			isInSampleMock.mockReturnValue( false );

			eventLoggingHelpers.logEvent( 'publish', null, null, null );

			expect( sendMock ).not.toHaveBeenCalled();
		} );
	} );

	describe( 'Test Kitchen soft dependency', () => {
		it( 'no-ops without throwing when mw.testKitchen is unavailable', () => {
			delete global.mw.testKitchen;

			expect(
				() => eventLoggingHelpers.logClickEvent( 'button', 'sidebar', {} )
			).not.toThrow();
			expect( getInstrumentMock ).not.toHaveBeenCalled();
			expect( sendMock ).not.toHaveBeenCalled();
		} );
	} );
} );
