<?php
/**
 * Support FreeCol: http://www.freecol.org/.
 *
 * @addtogroup Extensions
 *
 * @author Niklas Laxström
 * @copyright Copyright © 2008-2009, Niklas Laxström
 * @license http://www.gnu.org/copyleft/gpl.html GNU General Public License 2.0 or later
 */

class FreeColMessageGroup extends MessageGroup {
	protected $label = 'FreeCol (open source game)';
	protected $id    = 'out-freecol';
	protected $type  = 'freecol';

	protected   $fileDir  = '__BUG__';

	public function getPath() { return $this->fileDir; }
	public function setPath( $value ) { $this->fileDir = $value; }

	protected $codeMap = array(
		'cs' => 'cs_CZ',
		'es' => 'es_ES',
		'it' => 'it_IT',
		'no' => 'nb_NO',
		'pl' => 'pl_PL',
		'sv' => 'sv_SE',
		'nl-be' => 'nl_BE',
		'en-gb' => 'en_GB',
		'en-us' => 'en_US',
		'pt'    => 'pt_PT',
		'pt-pt' => 'pt_PT',
		'pt-br' => 'pt_BR',
	);

	protected $optional = array(
		'model.foundingFather.adamSmith.birthAndDeath', 'model.foundingFather.adamSmith.name',
		'model.foundingFather.bartolomeDeLasCasas.birthAndDeath', 'model.foundingFather.bartolomeDeLasCasas.name', 'model.foundingFather.benjaminFranklin.birthAndDeath',
		'model.foundingFather.benjaminFranklin.name', 'model.foundingFather.fatherJeanDeBrebeuf.birthAndDeath', 'model.foundingFather.fatherJeanDeBrebeuf.name',
		'model.foundingFather.ferdinandMagellan.birthAndDeath', 'model.foundingFather.ferdinandMagellan.name', 'model.foundingFather.francisDrake.birthAndDeath',
		'model.foundingFather.francisDrake.name', 'model.foundingFather.franciscoDeCoronado.birthAndDeath', 'model.foundingFather.franciscoDeCoronado.name',
		'model.foundingFather.georgeWashington.birthAndDeath', 'model.foundingFather.georgeWashington.name', 'model.foundingFather.henryHudson.birthAndDeath',
		'model.foundingFather.henryHudson.name', 'model.foundingFather.hernanCortes.birthAndDeath', 'model.foundingFather.hernanCortes.name',
		'model.foundingFather.hernandoDeSoto.birthAndDeath', 'model.foundingFather.hernandoDeSoto.name', 'model.foundingFather.jacobFugger.name',
		'model.foundingFather.janDeWitt.birthAndDeath', 'model.foundingFather.janDeWitt.name', 'model.foundingFather.johnPaulJones.birthAndDeath',
		'model.foundingFather.johnPaulJones.name', 'model.foundingFather.juanDeSepulveda.birthAndDeath', 'model.foundingFather.juanDeSepulveda.name',
		'model.foundingFather.laSalle.birthAndDeath', 'model.foundingFather.laSalle.name', 'model.foundingFather.paulRevere.birthAndDeath',
		'model.foundingFather.paulRevere.name', 'model.foundingFather.peterMinuit.birthAndDeath', 'model.foundingFather.peterMinuit.name',
		'model.foundingFather.peterStuyvesant.birthAndDeath', 'model.foundingFather.peterStuyvesant.name', 'model.foundingFather.pocahontas.birthAndDeath',
		'model.foundingFather.pocahontas.name', 'model.foundingFather.simonBolivar.birthAndDeath', 'model.foundingFather.simonBolivar.name',
		'model.foundingFather.thomasJefferson.birthAndDeath', 'model.foundingFather.thomasJefferson.name', 'model.foundingFather.thomasPaine.birthAndDeath',
		'model.foundingFather.thomasPaine.name', 'model.foundingFather.williamBrewster.birthAndDeath', 'model.foundingFather.williamBrewster.name',
		'model.foundingFather.williamPenn.birthAndDeath', 'model.foundingFather.williamPenn.name', 'model.goods.goodsAmount',
		'model.model.foundingFather.jacobFugger.birthAndDeath', 'model.nation.Apache.ruler', 'model.nation.Arawak.ruler',
		'model.nation.Aztec.ruler', 'model.nation.Cherokee.ruler', 'model.nation.Dutch.ruler',
		'model.nation.English.ruler', 'model.nation.French.ruler', 'model.nation.Inca.ruler',
		'model.nation.Iroquois.ruler', 'model.nation.Portuguese.Europe', 'model.nation.Portuguese.ruler',
		'model.nation.Sioux.ruler', 'model.nation.Spanish.ruler', 'model.nation.Tupi.ruler',
		'model.nation.danish.ruler', 'model.nation.danishREF.ruler', 'model.nation.dutch.settlementName.0',
		'model.nation.dutch.settlementName.1', 'model.nation.dutch.settlementName.10', 'model.nation.dutch.settlementName.11',
		'model.nation.dutch.settlementName.12', 'model.nation.dutch.settlementName.13', 'model.nation.dutch.settlementName.14',
		'model.nation.dutch.settlementName.15', 'model.nation.dutch.settlementName.16', 'model.nation.dutch.settlementName.17',
		'model.nation.dutch.settlementName.18', 'model.nation.dutch.settlementName.19', 'model.nation.dutch.settlementName.2',
		'model.nation.dutch.settlementName.20', 'model.nation.dutch.settlementName.21', 'model.nation.dutch.settlementName.22',
		'model.nation.dutch.settlementName.23', 'model.nation.dutch.settlementName.24', 'model.nation.dutch.settlementName.25',
		'model.nation.dutch.settlementName.26', 'model.nation.dutch.settlementName.27', 'model.nation.dutch.settlementName.28',
		'model.nation.dutch.settlementName.29', 'model.nation.dutch.settlementName.3', 'model.nation.dutch.settlementName.30',
		'model.nation.dutch.settlementName.31', 'model.nation.dutch.settlementName.4', 'model.nation.dutch.settlementName.5',
		'model.nation.dutch.settlementName.6', 'model.nation.dutch.settlementName.7', 'model.nation.dutch.settlementName.8',
		'model.nation.dutch.settlementName.9', 'model.nation.dutch.region.land.1', 'model.nation.dutch.region.land.10',
		'model.nation.dutch.region.land.2', 'model.nation.dutch.region.land.3', 'model.nation.dutch.region.land.4',
		'model.nation.dutch.region.land.5', 'model.nation.dutch.region.land.6', 'model.nation.dutch.region.land.7',
		'model.nation.dutch.region.land.8', 'model.nation.dutch.region.land.9', 'model.nation.dutch.region.mountain.1',
		'model.nation.dutch.region.mountain.2', 'model.nation.dutch.region.mountain.3', 'model.nation.dutch.region.mountain.4',
		'model.nation.dutch.region.mountain.5', 'model.nation.dutch.region.mountain.6', 'model.nation.dutch.region.mountain.7',
		'model.nation.dutch.region.mountain.8', 'model.nation.dutch.region.mountain.9', 'model.nation.dutch.region.river.1',
		'model.nation.dutch.region.river.2', 'model.nation.dutch.region.river.3', 'model.nation.dutch.region.river.4',
		'model.nation.dutch.region.river.5', 'model.nation.dutch.region.river.6', 'model.nation.dutch.region.river.7',
		'model.nation.dutch.region.river.8', 'model.nation.english.settlementName.0', 'model.nation.english.settlementName.1',
		'model.nation.english.settlementName.10', 'model.nation.english.settlementName.11', 'model.nation.english.settlementName.12',
		'model.nation.english.settlementName.13', 'model.nation.english.settlementName.14', 'model.nation.english.settlementName.15',
		'model.nation.english.settlementName.16', 'model.nation.english.settlementName.17', 'model.nation.english.settlementName.18',
		'model.nation.english.settlementName.19', 'model.nation.english.settlementName.2', 'model.nation.english.settlementName.20',
		'model.nation.english.settlementName.21', 'model.nation.english.settlementName.22', 'model.nation.english.settlementName.23',
		'model.nation.english.settlementName.24', 'model.nation.english.settlementName.25', 'model.nation.english.settlementName.26',
		'model.nation.english.settlementName.27', 'model.nation.english.settlementName.28', 'model.nation.english.settlementName.29',
		'model.nation.english.settlementName.3', 'model.nation.english.settlementName.30', 'model.nation.english.settlementName.31',
		'model.nation.english.settlementName.32', 'model.nation.english.settlementName.33', 'model.nation.english.settlementName.34',
		'model.nation.english.settlementName.35', 'model.nation.english.settlementName.4', 'model.nation.english.settlementName.5',
		'model.nation.english.settlementName.6', 'model.nation.english.settlementName.7', 'model.nation.english.settlementName.8',
		'model.nation.english.settlementName.9', 'model.nation.english.region.land.1', 'model.nation.english.region.land.10',
		'model.nation.english.region.land.2', 'model.nation.english.region.land.3', 'model.nation.english.region.land.4',
		'model.nation.english.region.land.5', 'model.nation.english.region.land.6', 'model.nation.english.region.land.7',
		'model.nation.english.region.land.8', 'model.nation.english.region.land.9', 'model.nation.english.region.mountain.1',
		'model.nation.english.region.mountain.2', 'model.nation.english.region.mountain.3', 'model.nation.english.region.mountain.4',
		'model.nation.english.region.mountain.5', 'model.nation.english.region.mountain.6', 'model.nation.english.region.mountain.7',
		'model.nation.english.region.mountain.8', 'model.nation.english.region.mountain.9', 'model.nation.english.region.river.1',
		'model.nation.english.region.river.10', 'model.nation.english.region.river.2', 'model.nation.english.region.river.3',
		'model.nation.english.region.river.4', 'model.nation.english.region.river.5', 'model.nation.english.region.river.6',
		'model.nation.english.region.river.7', 'model.nation.english.region.river.8', 'model.nation.english.region.river.9',
		'model.nation.french.settlementName.0', 'model.nation.french.settlementName.1', 'model.nation.french.settlementName.10',
		'model.nation.french.settlementName.11', 'model.nation.french.settlementName.12', 'model.nation.french.settlementName.13',
		'model.nation.french.settlementName.14', 'model.nation.french.settlementName.15', 'model.nation.french.settlementName.16',
		'model.nation.french.settlementName.17', 'model.nation.french.settlementName.18', 'model.nation.french.settlementName.19',
		'model.nation.french.settlementName.2', 'model.nation.french.settlementName.20', 'model.nation.french.settlementName.21',
		'model.nation.french.settlementName.22', 'model.nation.french.settlementName.23', 'model.nation.french.settlementName.24',
		'model.nation.french.settlementName.25', 'model.nation.french.settlementName.26', 'model.nation.french.settlementName.27',
		'model.nation.french.settlementName.28', 'model.nation.french.settlementName.29', 'model.nation.french.settlementName.3',
		'model.nation.french.settlementName.30', 'model.nation.french.settlementName.31', 'model.nation.french.settlementName.32',
		'model.nation.french.settlementName.33', 'model.nation.french.settlementName.34', 'model.nation.french.settlementName.35',
		'model.nation.french.settlementName.36', 'model.nation.french.settlementName.37', 'model.nation.french.settlementName.38',
		'model.nation.french.settlementName.39', 'model.nation.french.settlementName.4', 'model.nation.french.settlementName.40',
		'model.nation.french.settlementName.41', 'model.nation.french.settlementName.42', 'model.nation.french.settlementName.43',
		'model.nation.french.settlementName.44', 'model.nation.french.settlementName.45', 'model.nation.french.settlementName.46',
		'model.nation.french.settlementName.47', 'model.nation.french.settlementName.48', 'model.nation.french.settlementName.49',
		'model.nation.french.settlementName.5', 'model.nation.french.settlementName.50', 'model.nation.french.settlementName.51',
		'model.nation.french.settlementName.52', 'model.nation.french.settlementName.53', 'model.nation.french.settlementName.54',
		'model.nation.french.settlementName.55', 'model.nation.french.settlementName.56', 'model.nation.french.settlementName.57',
		'model.nation.french.settlementName.58', 'model.nation.french.settlementName.59', 'model.nation.french.settlementName.6',
		'model.nation.french.settlementName.60', 'model.nation.french.settlementName.61', 'model.nation.french.settlementName.62',
		'model.nation.french.settlementName.63', 'model.nation.french.settlementName.64', 'model.nation.french.settlementName.65',
		'model.nation.french.settlementName.7', 'model.nation.french.settlementName.8', 'model.nation.french.settlementName.9',
		'model.nation.french.region.land.1', 'model.nation.french.region.land.2', 'model.nation.french.region.land.3',
		'model.nation.french.region.land.4', 'model.nation.french.region.land.5', 'model.nation.french.region.land.6',
		'model.nation.french.region.land.7',
		'model.nation.french.region.mountain.1', 'model.nation.french.region.mountain.10', 'model.nation.french.region.mountain.2',
		'model.nation.french.region.mountain.3', 'model.nation.french.region.mountain.4', 'model.nation.french.region.mountain.5',
		'model.nation.french.region.mountain.6', 'model.nation.french.region.mountain.7', 'model.nation.french.region.mountain.8',
		'model.nation.french.region.mountain.9', 'model.nation.french.region.river.1', 'model.nation.french.region.river.10',
		'model.nation.french.region.river.2', 'model.nation.french.region.river.3', 'model.nation.french.region.river.4',
		'model.nation.french.region.river.5', 'model.nation.french.region.river.6', 'model.nation.french.region.river.7',
		'model.nation.french.region.river.8', 'model.nation.french.region.river.9', 'model.nation.portuguese.settlementName.0',
		'model.nation.portuguese.settlementName.1', 'model.nation.portuguese.settlementName.10', 'model.nation.portuguese.settlementName.11',
		'model.nation.portuguese.settlementName.12', 'model.nation.portuguese.settlementName.13', 'model.nation.portuguese.settlementName.14',
		'model.nation.portuguese.settlementName.15', 'model.nation.portuguese.settlementName.16', 'model.nation.portuguese.settlementName.17',
		'model.nation.portuguese.settlementName.18', 'model.nation.portuguese.settlementName.19', 'model.nation.portuguese.settlementName.2',
		'model.nation.portuguese.settlementName.20', 'model.nation.portuguese.settlementName.21', 'model.nation.portuguese.settlementName.22',
		'model.nation.portuguese.settlementName.23', 'model.nation.portuguese.settlementName.24', 'model.nation.portuguese.settlementName.25',
		'model.nation.portuguese.settlementName.26', 'model.nation.portuguese.settlementName.27', 'model.nation.portuguese.settlementName.28',
		'model.nation.portuguese.settlementName.29', 'model.nation.portuguese.settlementName.3', 'model.nation.portuguese.settlementName.4',
		'model.nation.portuguese.settlementName.5', 'model.nation.portuguese.settlementName.6', 'model.nation.portuguese.settlementName.7',
		'model.nation.portuguese.settlementName.8', 'model.nation.portuguese.settlementName.9', 'model.nation.refDutch.ruler',
		'model.nation.refEnglish.ruler', 'model.nation.refFrench.ruler', 'model.nation.refPortuguese.ruler',
		'model.nation.refSpanish.ruler', 'model.nation.russian.ruler', 'model.nation.russianREF.ruler',
		'model.nation.spanish.settlementName.0', 'model.nation.spanish.settlementName.1', 'model.nation.spanish.settlementName.10',
		'model.nation.spanish.settlementName.11', 'model.nation.spanish.settlementName.12', 'model.nation.spanish.settlementName.13',
		'model.nation.spanish.settlementName.14', 'model.nation.spanish.settlementName.15', 'model.nation.spanish.settlementName.16',
		'model.nation.spanish.settlementName.17', 'model.nation.spanish.settlementName.18', 'model.nation.spanish.settlementName.19',
		'model.nation.spanish.settlementName.2', 'model.nation.spanish.settlementName.20', 'model.nation.spanish.settlementName.21',
		'model.nation.spanish.settlementName.22', 'model.nation.spanish.settlementName.23', 'model.nation.spanish.settlementName.24',
		'model.nation.spanish.settlementName.25', 'model.nation.spanish.settlementName.26', 'model.nation.spanish.settlementName.27',
		'model.nation.spanish.settlementName.28', 'model.nation.spanish.settlementName.29', 'model.nation.spanish.settlementName.3',
		'model.nation.spanish.settlementName.30', 'model.nation.spanish.settlementName.31', 'model.nation.spanish.settlementName.32',
		'model.nation.spanish.settlementName.33', 'model.nation.spanish.settlementName.34', 'model.nation.spanish.settlementName.35',
		'model.nation.spanish.settlementName.36', 'model.nation.spanish.settlementName.37', 'model.nation.spanish.settlementName.38',
		'model.nation.spanish.settlementName.4', 'model.nation.spanish.settlementName.5', 'model.nation.spanish.settlementName.6',
		'model.nation.spanish.settlementName.7', 'model.nation.spanish.settlementName.8', 'model.nation.spanish.settlementName.9',
		'model.nation.spanish.region.land.1', 'model.nation.spanish.region.land.2', 'model.nation.spanish.region.land.3',
		'model.nation.spanish.region.land.4', 'model.nation.spanish.region.land.5', 'model.nation.spanish.region.river.1',
		'model.nation.spanish.region.river.2', 'model.nation.swedish.europe', 'model.nation.swedish.ruler',
		'model.nation.swedishREF.ruler', 'model.unit.occupation.activeNoMovesLeft',
		'shipName.3.0', 'model.nation.spanish.region.mountain.1', 'model.nation.spanish.region.mountain.2',
		'model.nation.spanish.region.mountain.3', 'model.nation.spanish.region.mountain.4', 'model.nation.spanish.region.mountain.5',
		'model.nation.spanish.region.river.3', 'model.nation.spanish.region.river.4', 'model.nation.spanish.region.river.5',
		'model.region.default', 'model.nation.danish.settlementName.0', 'model.nation.danish.settlementName.1',
		'model.nation.danish.settlementName.2',
		'model.nation.danish.settlementName.10', 'model.nation.danish.settlementName.11', 'model.nation.danish.settlementName.12',
		'model.nation.danish.settlementName.3', 'model.nation.danish.settlementName.4', 'model.nation.danish.settlementName.5',
		'model.nation.danish.settlementName.6', 'model.nation.danish.settlementName.7', 'model.nation.danish.settlementName.8',
		'model.nation.danish.settlementName.9', 'model.nation.danish.region.land.1', 'model.nation.danish.region.land.2',
		'model.nation.danish.region.land.3', 'model.nation.danish.region.land.4', 'model.nation.danish.region.land.5',
		'model.nation.danish.region.land.6', 'model.nation.danish.region.mountain.1', 'model.nation.danish.region.mountain.2',
		'model.nation.danish.region.mountain.3', 'model.nation.danish.region.mountain.4', 'model.nation.danish.region.mountain.5',
		'model.nation.danish.region.mountain.6', 'model.nation.danish.region.river.1', 'model.nation.danish.region.river.2',
		'model.nation.danish.region.river.3', 'model.nation.russian.settlementName.0', 'model.nation.russian.settlementName.1',
		'model.nation.russian.settlementName.10',
		'model.nation.russian.settlementName.11', 'model.nation.russian.settlementName.12', 'model.nation.russian.settlementName.13',
		'model.nation.russian.settlementName.14', 'model.nation.russian.settlementName.15', 'model.nation.russian.settlementName.16',
		'model.nation.russian.settlementName.17', 'model.nation.russian.settlementName.18', 'model.nation.russian.settlementName.19',
		'model.nation.russian.settlementName.2', 'model.nation.russian.settlementName.20', 'model.nation.russian.settlementName.21',
		'model.nation.russian.settlementName.22', 'model.nation.russian.settlementName.23', 'model.nation.russian.settlementName.3',
		'model.nation.russian.settlementName.4', 'model.nation.russian.settlementName.5', 'model.nation.russian.settlementName.6',
		'model.nation.russian.settlementName.7', 'model.nation.russian.settlementName.8', 'model.nation.russian.settlementName.9',
		'model.nation.russian.region.land.1', 'model.nation.russian.region.land.2', 'model.nation.russian.region.land.3',
		'model.nation.russian.region.land.4', 'model.nation.russian.region.land.5', 'model.nation.russian.region.mountain.1',
		'model.nation.russian.region.mountain.2', 'model.nation.russian.region.mountain.3', 'model.nation.russian.region.mountain.4',
		'model.nation.russian.region.mountain.5', 'model.nation.russian.region.river.1', 'model.nation.russian.region.river.2',
		'model.nation.russian.region.river.3', 'model.nation.russian.region.river.4', 'model.nation.swedish.settlementName.0',
		'model.nation.swedish.settlementName.1', 'model.nation.swedish.settlementName.10', 'model.nation.swedish.settlementName.11',
		'model.nation.swedish.settlementName.12', 'model.nation.swedish.settlementName.13', 'model.nation.swedish.settlementName.14',
		'model.nation.swedish.settlementName.15', 'model.nation.swedish.settlementName.16', 'model.nation.swedish.settlementName.17',
		'model.nation.swedish.settlementName.18', 'model.nation.swedish.settlementName.19', 'model.nation.swedish.settlementName.2',
		'model.nation.swedish.settlementName.20', 'model.nation.swedish.settlementName.21', 'model.nation.swedish.settlementName.3',
		'model.nation.swedish.settlementName.4', 'model.nation.swedish.settlementName.5', 'model.nation.swedish.settlementName.6',
		'model.nation.swedish.settlementName.7', 'model.nation.swedish.settlementName.8', 'model.nation.swedish.settlementName.9',
		'model.nation.swedish.region.land.1', 'model.nation.swedish.region.land.2', 'model.nation.swedish.region.land.3',
		'model.nation.swedish.region.river.1', 'model.nation.swedish.region.river.2', 'model.nation.swedish.region.river.3',
		'model.nation.swedish.region.river.4',
		'model.nation.apache.settlementName.0', 'model.nation.apache.settlementName.10', 'model.nation.apache.settlementName.11',
		'model.nation.apache.settlementName.12', 'model.nation.apache.settlementName.13', 'model.nation.apache.settlementName.14',
		'model.nation.apache.settlementName.15', 'model.nation.apache.settlementName.16', 'model.nation.apache.settlementName.17',
		'model.nation.apache.settlementName.18', 'model.nation.apache.settlementName.19', 'model.nation.apache.settlementName.1',
		'model.nation.apache.settlementName.20', 'model.nation.apache.settlementName.21', 'model.nation.apache.settlementName.22',
		'model.nation.apache.settlementName.23', 'model.nation.apache.settlementName.24', 'model.nation.apache.settlementName.25',
		'model.nation.apache.settlementName.26', 'model.nation.apache.settlementName.27', 'model.nation.apache.settlementName.28',
		'model.nation.apache.settlementName.29', 'model.nation.apache.settlementName.2', 'model.nation.apache.settlementName.30',
		'model.nation.apache.settlementName.3', 'model.nation.apache.settlementName.40', 'model.nation.apache.settlementName.41',
		'model.nation.apache.settlementName.31', 'model.nation.apache.settlementName.32', 'model.nation.apache.settlementName.33',
		'model.nation.apache.settlementName.34', 'model.nation.apache.settlementName.35', 'model.nation.apache.settlementName.36',
		'model.nation.apache.settlementName.37', 'model.nation.apache.settlementName.38', 'model.nation.apache.settlementName.39',
		'model.nation.apache.settlementName.42', 'model.nation.apache.settlementName.43', 'model.nation.apache.settlementName.44',
		'model.nation.apache.settlementName.45', 'model.nation.apache.settlementName.46', 'model.nation.apache.settlementName.47',
		'model.nation.apache.settlementName.48', 'model.nation.apache.settlementName.49', 'model.nation.apache.settlementName.4',
		'model.nation.apache.settlementName.50', 'model.nation.apache.settlementName.5', 'model.nation.apache.settlementName.6',
		'model.nation.apache.settlementName.7', 'model.nation.apache.settlementName.8', 'model.nation.apache.settlementName.9',
		'model.nation.arawak.settlementName.0', 'model.nation.arawak.settlementName.10', 'model.nation.arawak.settlementName.11',
		'model.nation.arawak.settlementName.12', 'model.nation.arawak.settlementName.13', 'model.nation.arawak.settlementName.14',
		'model.nation.arawak.settlementName.15', 'model.nation.arawak.settlementName.16', 'model.nation.arawak.settlementName.17',
		'model.nation.arawak.settlementName.18', 'model.nation.arawak.settlementName.19', 'model.nation.arawak.settlementName.1',
		'model.nation.arawak.settlementName.20', 'model.nation.arawak.settlementName.21', 'model.nation.arawak.settlementName.22',
		'model.nation.arawak.settlementName.23', 'model.nation.arawak.settlementName.24', 'model.nation.arawak.settlementName.25',
		'model.nation.arawak.settlementName.26', 'model.nation.arawak.settlementName.27', 'model.nation.arawak.settlementName.28',
		'model.nation.arawak.settlementName.29', 'model.nation.arawak.settlementName.2', 'model.nation.arawak.settlementName.30',
		'model.nation.arawak.settlementName.3', 'model.nation.arawak.settlementName.40', 'model.nation.arawak.settlementName.41',
		'model.nation.arawak.settlementName.31', 'model.nation.arawak.settlementName.32', 'model.nation.arawak.settlementName.33',
		'model.nation.arawak.settlementName.34', 'model.nation.arawak.settlementName.35', 'model.nation.arawak.settlementName.36',
		'model.nation.arawak.settlementName.37', 'model.nation.arawak.settlementName.38', 'model.nation.arawak.settlementName.39',
		'model.nation.arawak.settlementName.42', 'model.nation.arawak.settlementName.43', 'model.nation.arawak.settlementName.44',
		'model.nation.arawak.settlementName.45', 'model.nation.arawak.settlementName.46', 'model.nation.arawak.settlementName.47',
		'model.nation.arawak.settlementName.48', 'model.nation.arawak.settlementName.49', 'model.nation.arawak.settlementName.4',
		'model.nation.arawak.settlementName.5', 'model.nation.arawak.settlementName.6', 'model.nation.arawak.settlementName.7',
		'model.nation.arawak.settlementName.50', 'model.nation.arawak.settlementName.51', 'model.nation.arawak.settlementName.52',
		'model.nation.arawak.settlementName.53', 'model.nation.arawak.settlementName.54', 'model.nation.arawak.settlementName.55',
		'model.nation.arawak.settlementName.56', 'model.nation.arawak.settlementName.57', 'model.nation.arawak.settlementName.58',
		'model.nation.arawak.settlementName.8', 'model.nation.arawak.settlementName.9', 'model.nation.aztec.settlementName.0',
		'model.nation.aztec.settlementName.10', 'model.nation.aztec.settlementName.11', 'model.nation.aztec.settlementName.12',
		'model.nation.aztec.settlementName.13', 'model.nation.aztec.settlementName.14', 'model.nation.aztec.settlementName.15',
		'model.nation.aztec.settlementName.16', 'model.nation.aztec.settlementName.17', 'model.nation.aztec.settlementName.18',
		'model.nation.aztec.settlementName.19', 'model.nation.aztec.settlementName.1', 'model.nation.aztec.settlementName.20',
		'model.nation.aztec.settlementName.2', 'model.nation.aztec.settlementName.30', 'model.nation.aztec.settlementName.31',
		'model.nation.aztec.settlementName.21', 'model.nation.aztec.settlementName.22', 'model.nation.aztec.settlementName.23',
		'model.nation.aztec.settlementName.24', 'model.nation.aztec.settlementName.25', 'model.nation.aztec.settlementName.26',
		'model.nation.aztec.settlementName.27', 'model.nation.aztec.settlementName.28', 'model.nation.aztec.settlementName.29',
		'model.nation.aztec.settlementName.32', 'model.nation.aztec.settlementName.33', 'model.nation.aztec.settlementName.34',
		'model.nation.aztec.settlementName.35', 'model.nation.aztec.settlementName.36', 'model.nation.aztec.settlementName.37',
		'model.nation.aztec.settlementName.38', 'model.nation.aztec.settlementName.39', 'model.nation.aztec.settlementName.3',
		'model.nation.aztec.settlementName.40', 'model.nation.aztec.settlementName.41', 'model.nation.aztec.settlementName.42',
		'model.nation.aztec.settlementName.43', 'model.nation.aztec.settlementName.44', 'model.nation.aztec.settlementName.45',
		'model.nation.aztec.settlementName.46', 'model.nation.aztec.settlementName.47', 'model.nation.aztec.settlementName.48',
		'model.nation.aztec.settlementName.49', 'model.nation.aztec.settlementName.4', 'model.nation.aztec.settlementName.50',
		'model.nation.aztec.settlementName.5', 'model.nation.aztec.settlementName.60', 'model.nation.aztec.settlementName.61',
		'model.nation.aztec.settlementName.51', 'model.nation.aztec.settlementName.52', 'model.nation.aztec.settlementName.53',
		'model.nation.aztec.settlementName.54', 'model.nation.aztec.settlementName.55', 'model.nation.aztec.settlementName.56',
		'model.nation.aztec.settlementName.57', 'model.nation.aztec.settlementName.58', 'model.nation.aztec.settlementName.59',
		'model.nation.aztec.settlementName.62', 'model.nation.aztec.settlementName.63', 'model.nation.aztec.settlementName.64',
		'model.nation.aztec.settlementName.65', 'model.nation.aztec.settlementName.66', 'model.nation.aztec.settlementName.67',
		'model.nation.aztec.settlementName.68', 'model.nation.aztec.settlementName.69', 'model.nation.aztec.settlementName.6',
		'model.nation.aztec.settlementName.7', 'model.nation.aztec.settlementName.8', 'model.nation.aztec.settlementName.9',
		'model.nation.aztec.settlementName.70', 'model.nation.aztec.settlementName.71', 'model.nation.aztec.settlementName.72',
		'model.nation.aztec.settlementName.73', 'model.nation.aztec.settlementName.74', 'model.nation.aztec.settlementName.75',
		'model.nation.cherokee.settlementName.0', 'model.nation.cherokee.settlementName.10', 'model.nation.cherokee.settlementName.11',
		'model.nation.cherokee.settlementName.12', 'model.nation.cherokee.settlementName.13', 'model.nation.cherokee.settlementName.14',
		'model.nation.cherokee.settlementName.15', 'model.nation.cherokee.settlementName.16', 'model.nation.cherokee.settlementName.17',
		'model.nation.cherokee.settlementName.18', 'model.nation.cherokee.settlementName.19', 'model.nation.cherokee.settlementName.1',
		'model.nation.cherokee.settlementName.20', 'model.nation.cherokee.settlementName.21', 'model.nation.cherokee.settlementName.22',
		'model.nation.cherokee.settlementName.23', 'model.nation.cherokee.settlementName.24', 'model.nation.cherokee.settlementName.25',
		'model.nation.cherokee.settlementName.26', 'model.nation.cherokee.settlementName.27', 'model.nation.cherokee.settlementName.28',
		'model.nation.cherokee.settlementName.29', 'model.nation.cherokee.settlementName.2', 'model.nation.cherokee.settlementName.30',
		'model.nation.cherokee.settlementName.3', 'model.nation.cherokee.settlementName.40', 'model.nation.cherokee.settlementName.41',
		'model.nation.cherokee.settlementName.31', 'model.nation.cherokee.settlementName.32', 'model.nation.cherokee.settlementName.33',
		'model.nation.cherokee.settlementName.34', 'model.nation.cherokee.settlementName.35', 'model.nation.cherokee.settlementName.36',
		'model.nation.cherokee.settlementName.37', 'model.nation.cherokee.settlementName.38', 'model.nation.cherokee.settlementName.39',
		'model.nation.cherokee.settlementName.42', 'model.nation.cherokee.settlementName.43', 'model.nation.cherokee.settlementName.44',
		'model.nation.cherokee.settlementName.45', 'model.nation.cherokee.settlementName.46', 'model.nation.cherokee.settlementName.47',
		'model.nation.cherokee.settlementName.48', 'model.nation.cherokee.settlementName.49', 'model.nation.cherokee.settlementName.4',
		'model.nation.cherokee.settlementName.5', 'model.nation.cherokee.settlementName.6', 'model.nation.cherokee.settlementName.7',
		'model.nation.cherokee.settlementName.8', 'model.nation.cherokee.settlementName.9', 'model.nation.inca.settlementName.0',
		'model.nation.inca.settlementName.10', 'model.nation.inca.settlementName.11', 'model.nation.inca.settlementName.12',
		'model.nation.inca.settlementName.13', 'model.nation.inca.settlementName.14', 'model.nation.inca.settlementName.15',
		'model.nation.inca.settlementName.16', 'model.nation.inca.settlementName.17', 'model.nation.inca.settlementName.18',
		'model.nation.inca.settlementName.19', 'model.nation.inca.settlementName.1', 'model.nation.inca.settlementName.20',
		'model.nation.inca.settlementName.2', 'model.nation.inca.settlementName.30', 'model.nation.inca.settlementName.31',
		'model.nation.inca.settlementName.21', 'model.nation.inca.settlementName.22', 'model.nation.inca.settlementName.23',
		'model.nation.inca.settlementName.24', 'model.nation.inca.settlementName.25', 'model.nation.inca.settlementName.26',
		'model.nation.inca.settlementName.27', 'model.nation.inca.settlementName.28', 'model.nation.inca.settlementName.29',
		'model.nation.inca.settlementName.32', 'model.nation.inca.settlementName.33', 'model.nation.inca.settlementName.34',
		'model.nation.inca.settlementName.35', 'model.nation.inca.settlementName.36', 'model.nation.inca.settlementName.37',
		'model.nation.inca.settlementName.38', 'model.nation.inca.settlementName.39', 'model.nation.inca.settlementName.3',
		'model.nation.inca.settlementName.40', 'model.nation.inca.settlementName.41', 'model.nation.inca.settlementName.42',
		'model.nation.inca.settlementName.43', 'model.nation.inca.settlementName.44', 'model.nation.inca.settlementName.45',
		'model.nation.inca.settlementName.46', 'model.nation.inca.settlementName.47', 'model.nation.inca.settlementName.48',
		'model.nation.inca.settlementName.49', 'model.nation.inca.settlementName.4', 'model.nation.inca.settlementName.50',
		'model.nation.inca.settlementName.5', 'model.nation.inca.settlementName.60', 'model.nation.inca.settlementName.61',
		'model.nation.inca.settlementName.51', 'model.nation.inca.settlementName.52', 'model.nation.inca.settlementName.53',
		'model.nation.inca.settlementName.54', 'model.nation.inca.settlementName.55', 'model.nation.inca.settlementName.56',
		'model.nation.inca.settlementName.57', 'model.nation.inca.settlementName.58', 'model.nation.inca.settlementName.59',
		'model.nation.inca.settlementName.62', 'model.nation.inca.settlementName.63', 'model.nation.inca.settlementName.64',
		'model.nation.inca.settlementName.65', 'model.nation.inca.settlementName.66', 'model.nation.inca.settlementName.67',
		'model.nation.inca.settlementName.68', 'model.nation.inca.settlementName.69', 'model.nation.inca.settlementName.6',
		'model.nation.inca.settlementName.70', 'model.nation.inca.settlementName.71', 'model.nation.inca.settlementName.72',
		'model.nation.inca.settlementName.73', 'model.nation.inca.settlementName.74', 'model.nation.inca.settlementName.75',
		'model.nation.inca.settlementName.76', 'model.nation.inca.settlementName.77', 'model.nation.inca.settlementName.78',
		'model.nation.inca.settlementName.79', 'model.nation.inca.settlementName.7', 'model.nation.inca.settlementName.80',
		'model.nation.inca.settlementName.81', 'model.nation.inca.settlementName.82', 'model.nation.inca.settlementName.83',
		'model.nation.inca.settlementName.84', 'model.nation.inca.settlementName.85', 'model.nation.inca.settlementName.8',
		'model.nation.inca.settlementName.9', 'model.nation.iroquois.settlementName.0', 'model.nation.iroquois.settlementName.10',
		'model.nation.iroquois.settlementName.1', 'model.nation.iroquois.settlementName.20', 'model.nation.iroquois.settlementName.21',
		'model.nation.iroquois.settlementName.11', 'model.nation.iroquois.settlementName.12', 'model.nation.iroquois.settlementName.13',
		'model.nation.iroquois.settlementName.14', 'model.nation.iroquois.settlementName.15', 'model.nation.iroquois.settlementName.16',
		'model.nation.iroquois.settlementName.17', 'model.nation.iroquois.settlementName.18', 'model.nation.iroquois.settlementName.19',
		'model.nation.iroquois.settlementName.22', 'model.nation.iroquois.settlementName.23', 'model.nation.iroquois.settlementName.24',
		'model.nation.iroquois.settlementName.25', 'model.nation.iroquois.settlementName.26', 'model.nation.iroquois.settlementName.27',
		'model.nation.iroquois.settlementName.28', 'model.nation.iroquois.settlementName.29', 'model.nation.iroquois.settlementName.2',
		'model.nation.iroquois.settlementName.30', 'model.nation.iroquois.settlementName.31', 'model.nation.iroquois.settlementName.32',
		'model.nation.iroquois.settlementName.33', 'model.nation.iroquois.settlementName.34', 'model.nation.iroquois.settlementName.35',
		'model.nation.iroquois.settlementName.36', 'model.nation.iroquois.settlementName.37', 'model.nation.iroquois.settlementName.38',
		'model.nation.iroquois.settlementName.39', 'model.nation.iroquois.settlementName.3', 'model.nation.iroquois.settlementName.40',
		'model.nation.iroquois.settlementName.4', 'model.nation.iroquois.settlementName.50', 'model.nation.iroquois.settlementName.51',
		'model.nation.iroquois.settlementName.41', 'model.nation.iroquois.settlementName.42', 'model.nation.iroquois.settlementName.43',
		'model.nation.iroquois.settlementName.44', 'model.nation.iroquois.settlementName.45', 'model.nation.iroquois.settlementName.46',
		'model.nation.iroquois.settlementName.47', 'model.nation.iroquois.settlementName.48', 'model.nation.iroquois.settlementName.49',
		'model.nation.iroquois.settlementName.52', 'model.nation.iroquois.settlementName.53', 'model.nation.iroquois.settlementName.54',
		'model.nation.iroquois.settlementName.55', 'model.nation.iroquois.settlementName.56', 'model.nation.iroquois.settlementName.57',
		'model.nation.iroquois.settlementName.58', 'model.nation.iroquois.settlementName.5', 'model.nation.iroquois.settlementName.6',
		'model.nation.iroquois.settlementName.7', 'model.nation.iroquois.settlementName.8', 'model.nation.iroquois.settlementName.9',
		'model.nation.sioux.settlementName.0', 'model.nation.sioux.settlementName.10', 'model.nation.sioux.settlementName.11',
		'model.nation.sioux.settlementName.12', 'model.nation.sioux.settlementName.13', 'model.nation.sioux.settlementName.14',
		'model.nation.sioux.settlementName.15', 'model.nation.sioux.settlementName.16', 'model.nation.sioux.settlementName.17',
		'model.nation.sioux.settlementName.18', 'model.nation.sioux.settlementName.19', 'model.nation.sioux.settlementName.1',
		'model.nation.sioux.settlementName.20', 'model.nation.sioux.settlementName.21', 'model.nation.sioux.settlementName.22',
		'model.nation.sioux.settlementName.23', 'model.nation.sioux.settlementName.24', 'model.nation.sioux.settlementName.25',
		'model.nation.sioux.settlementName.26', 'model.nation.sioux.settlementName.27', 'model.nation.sioux.settlementName.28',
		'model.nation.sioux.settlementName.29', 'model.nation.sioux.settlementName.2', 'model.nation.sioux.settlementName.30',
		'model.nation.sioux.settlementName.3', 'model.nation.sioux.settlementName.40', 'model.nation.sioux.settlementName.41',
		'model.nation.sioux.settlementName.31', 'model.nation.sioux.settlementName.32', 'model.nation.sioux.settlementName.33',
		'model.nation.sioux.settlementName.34', 'model.nation.sioux.settlementName.35', 'model.nation.sioux.settlementName.36',
		'model.nation.sioux.settlementName.37', 'model.nation.sioux.settlementName.38', 'model.nation.sioux.settlementName.39',
		'model.nation.sioux.settlementName.42', 'model.nation.sioux.settlementName.43', 'model.nation.sioux.settlementName.44',
		'model.nation.sioux.settlementName.45', 'model.nation.sioux.settlementName.46', 'model.nation.sioux.settlementName.4',
		'model.nation.sioux.settlementName.5', 'model.nation.sioux.settlementName.6', 'model.nation.sioux.settlementName.7',
		'model.nation.sioux.settlementName.8', 'model.nation.sioux.settlementName.9', 'model.nation.tupi.settlementName.0',
		'model.nation.tupi.settlementName.10', 'model.nation.tupi.settlementName.11', 'model.nation.tupi.settlementName.12',
		'model.nation.tupi.settlementName.13', 'model.nation.tupi.settlementName.14', 'model.nation.tupi.settlementName.15',
		'model.nation.tupi.settlementName.16', 'model.nation.tupi.settlementName.17', 'model.nation.tupi.settlementName.18',
		'model.nation.tupi.settlementName.19', 'model.nation.tupi.settlementName.1', 'model.nation.tupi.settlementName.20',
		'model.nation.tupi.settlementName.2', 'model.nation.tupi.settlementName.30', 'model.nation.tupi.settlementName.31',
		'model.nation.tupi.settlementName.21', 'model.nation.tupi.settlementName.22', 'model.nation.tupi.settlementName.23',
		'model.nation.tupi.settlementName.24', 'model.nation.tupi.settlementName.25', 'model.nation.tupi.settlementName.26',
		'model.nation.tupi.settlementName.27', 'model.nation.tupi.settlementName.28', 'model.nation.tupi.settlementName.29',
		'model.nation.tupi.settlementName.32', 'model.nation.tupi.settlementName.33', 'model.nation.tupi.settlementName.34',
		'model.nation.tupi.settlementName.35', 'model.nation.tupi.settlementName.36', 'model.nation.tupi.settlementName.37',
		'model.nation.tupi.settlementName.38', 'model.nation.tupi.settlementName.39', 'model.nation.tupi.settlementName.3',
		'model.nation.tupi.settlementName.40', 'model.nation.tupi.settlementName.41', 'model.nation.tupi.settlementName.42',
		'model.nation.tupi.settlementName.43', 'model.nation.tupi.settlementName.44', 'model.nation.tupi.settlementName.45',
		'model.nation.tupi.settlementName.46', 'model.nation.tupi.settlementName.47', 'model.nation.tupi.settlementName.48',
		'model.nation.tupi.settlementName.49', 'model.nation.tupi.settlementName.4', 'model.nation.tupi.settlementName.50',
		'model.nation.tupi.settlementName.5', 'model.nation.tupi.settlementName.6', 'model.nation.tupi.settlementName.7',
		'model.nation.tupi.settlementName.51', 'model.nation.tupi.settlementName.52', 'model.nation.tupi.settlementName.53',
		'model.nation.tupi.settlementName.8', 'model.nation.tupi.settlementName.9',
	);

	protected $ignored = array(
		'headerFont',
	);

	public function getMessageFile( $code ) {
		if ( $code == 'en' ) {
			return 'FreeColMessages.properties';
		} else {
			if ( isset( $this->codeMap[$code] ) ) {
				$code = $this->codeMap[$code];
			}
			return "FreeColMessages_$code.properties";
		}
	}

	protected function getFileLocation( $code ) {
		return $this->fileDir . '/' . $this->getMessageFile( $code );
	}

	public function getReader( $code ) {
		return new JavaFormatReader( $this->getFileLocation( $code ) );
	}

	public function getWriter() {
		return new JavaFormatWriter( $this );
	}
}
