-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/Translate/sql/abstractSchemaChanges/patch-revtag-int-to-bigint-unsigned.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE revtag
  ALTER rt_page TYPE BIGINT;
ALTER TABLE revtag
  ALTER rt_revision TYPE BIGINT;
