-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/Translate/sql/abstractSchemaChanges/patch-translate_message_group_subscriptions-composite-primary-key.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX translate_tmgs_group;
ALTER TABLE translate_message_group_subscriptions
  DROP CONSTRAINT translate_message_group_subscriptions_pkey;
ALTER TABLE translate_message_group_subscriptions
  DROP tmgs_subscription_id;
ALTER TABLE translate_message_group_subscriptions
  ADD PRIMARY KEY (tmgs_group, tmgs_user_id);
