---
BASIC:
  id: out-shapado-default
  label: Shapado - Default
  description: "{{int:bw-desc-shapado}}"
  namespace: NS_SHAPADO
  display: out/shapado/default
  class: FileBasedMessageGroup

FILES:
  class: YamlFFS
  sourcePattern: %GROUPROOT%/shapado/config/locales/default/%CODE%.yml
  codeAsRoot: 1
  targetPattern: %CODE%.yml
  codeMap:
    es-ar: es-AR
    pt:    pt-PT
    pt-br: pt-BR
    sr-ec: sr-EC
    zh-cn: zh-CN
    zh-tw: zh-TW
    zh-hant: zh-HANT

MANGLER:
  class: StringMatcher
  prefix: default-
  patterns:
    - "*"
