-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-translate_messageindex-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX tmi_key;
CREATE TEMPORARY TABLE /*_*/__temp__translate_messageindex AS
SELECT  tmi_key,  tmi_value
FROM  /*_*/translate_messageindex;
DROP  TABLE  /*_*/translate_messageindex;
CREATE TABLE  /*_*/translate_messageindex (    tmi_key BLOB NOT NULL,    tmi_value BLOB NOT NULL,    PRIMARY KEY(tmi_key)  );
INSERT INTO  /*_*/translate_messageindex (tmi_key, tmi_value)
SELECT  tmi_key,  tmi_value
FROM  /*_*/__temp__translate_messageindex;
DROP  TABLE /*_*/__temp__translate_messageindex;