-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-translate_reviews-unsigned.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__translate_reviews AS
SELECT
  trr_user,
  trr_page,
  trr_revision
FROM /*_*/translate_reviews;
DROP TABLE /*_*/translate_reviews;


CREATE TABLE /*_*/translate_reviews (
    trr_user INTEGER UNSIGNED NOT NULL,
    trr_page INTEGER UNSIGNED NOT NULL,
    trr_revision BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY(trr_page, trr_revision, trr_user)
  );
INSERT INTO /*_*/translate_reviews (trr_user, trr_page, trr_revision)
SELECT
  trr_user,
  trr_page,
  trr_revision
FROM
  /*_*/__temp__translate_reviews;
DROP TABLE /*_*/__temp__translate_reviews;
