-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-translate_tmt-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX tms_sid_lang;
CREATE TEMPORARY TABLE /*_*/__temp__translate_tmt AS
SELECT  tmt_sid,  tmt_lang,  tmt_text
FROM  /*_*/translate_tmt;
DROP  TABLE  /*_*/translate_tmt;
CREATE TABLE  /*_*/translate_tmt (    tmt_sid INTEGER UNSIGNED NOT NULL,    tmt_lang BLOB NOT NULL,    tmt_text BLOB NOT NULL,    PRIMARY KEY(tmt_sid, tmt_lang)  );
INSERT INTO  /*_*/translate_tmt (tmt_sid, tmt_lang, tmt_text)
SELECT  tmt_sid,  tmt_lang,  tmt_text
FROM  /*_*/__temp__translate_tmt;
DROP  TABLE /*_*/__temp__translate_tmt;