-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-translate_messageindex-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX tmi_key ON  /*_*/translate_messageindex;
ALTER TABLE  /*_*/translate_messageindex
ADD  PRIMARY KEY (tmi_key);