-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/Translate/sql/abstractSchemaChanges/patch-translate_message_group_subscriptions-composite-primary-key.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/translate_message_group_subscriptions
  MODIFY tmgs_subscription_id INT UNSIGNED NOT NULL;
DROP INDEX translate_tmgs_group ON /*_*/translate_message_group_subscriptions;
DROP INDEX `primary` ON /*_*/translate_message_group_subscriptions;
ALTER TABLE /*_*/translate_message_group_subscriptions
  DROP tmgs_subscription_id;
ALTER TABLE /*_*/translate_message_group_subscriptions
  ADD PRIMARY KEY (tmgs_group, tmgs_user_id);
