-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/Translate/sql/abstractSchemaChanges/patch-revtag-int-to-bigint-unsigned.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/revtag
  CHANGE rt_page rt_page BIGINT UNSIGNED NOT NULL,
  CHANGE rt_revision rt_revision BIGINT UNSIGNED NOT NULL;
